### ISSUE TITLE
Deployment to Azure is failing

### ISSUE THREAD

**Issue by msnehagup** [0GiS0/audio-azure-functions#1]
Deployment to Azure using the deployment template is failing while trying to deploy the 'Microsoft.Web/sites/sourcecontrols' resource type with error:
> {
>   "status": "Failed",
>   "error": {
>     "code": "ResourceDeploymentFailure",
>     "message": "The resource operation completed with terminal provisioning state 'Failed'."
>   }
> }

The function app gets created, but **there are no functions within the function app**.

Deployment Center of the function app shows the below error:
> Your function app is targeting V2, but Azure host has function version V1, \r\nplease change the version using the portal or update your 'FUNCTIONS_EXTENSION_VERSION' appsetting and retry

![image](https://user-images.githubusercontent.com/45184761/52670091-946eb480-2ecc-11e9-89a6-20b0dd8e8d4a.png)

**Comment by 0GiS0** [comment]
Hi @msnehagup ,

I'm sorry for the delay. I'll take a look as soon as I can and I fixed.

Thanks

**Comment by 0GiS0** [comment]
Now it's fixed.

Thanks!
